{
  "project_id": "{PROJECT_NAME}",
  "project_root": ".",
  "revision": 0,
  "current_agent": "agent",
  "assigned_agent": "agent",
  "phase": "initialization",
  "status": "in_progress",
  "task": {
    "id": "T-001",
    "title": "Project initialization",
    "goal": "Initialize {PROJECT_NAME}",
    "owner": "agent",
    "status": "active",
    "next_action": "agent starts requirements analysis for {PROJECT_NAME}",
    "acceptance": [],
    "verify_commands": [],
    "rule_tags": [],
    "last_output": "",
    "blockers": [],
    "decision_ids": [],
    "cli_sessions": {},
    "placeholder": true
  },
  "task_context": {"day": 0, "topic": "", "project_dir": ""},
  "goal": null,
  "workflow": null,
  "goal_queue": [],
  "goal_history": [],
  "last_wake_hash": "",
  "automation_enabled": true,
  "last_dispatch_id": "",
  "last_wake_status": "",
  "last_woken_at": "",
  "wake_count": 0,
  "files_changed": [],
  "verify_commands": [],
  "updated_at": ""
}
